- name: Pull and run a Docker image
  hosts: all
  tasks:
    - name: Pull a Docker image
      community.docker.docker_image:
        name: "flaskapi"
        source: pull

    - name: Run a Docker container
      community.docker.docker_container:
        name: "adoring_rubin"
        image: "flaskapi"
        state: started
