- name: Pull and run a Docker image
  hosts: localhost
  collections:
    - community.docker
  tasks:
    - name: Pull a Docker image
      docker_image:
        name: "your_image_name:tag"
        source: pull

    - name: Run a Docker container
      docker_container:
        name: "my_container"
        image: "your_image_name:tag"
        state: started
