---
- name: Deploy Image with Ansible
  hosts: localhost
  become: yes
  tasks:
  - name: Find pip location
    command: which pip3
    register: pip_location
    ignore_errors: yes

  - name: Print pip location
    debug:
      msg: "The location of pip is {{ pip_location.stdout }}"
    when: pip_location.rc == 0

  - name: Print error if pip is not found
    debug:
      msg: "pip is not found"
    when: pip_location.rc != 0
  - name: Ensure Docker SDK for Python is installed
    pip:
      name: docker
      executable: "{{ pip_location.stdout }}"
    when: pip_location.stdout != ''


  - name: Login to DockerHub
    docker_login:
      username: piggly
      password: Duckery4m**p

  - name: Pull a Docker Image
    docker_image:
      name: flaskapi
      source: pull

  - name: Run a Docker Container
    docker_container:
      name: adoring_rubin
      image: flaskapi
      state: started
      ports:
        - "8099:8099"
