---
- name: Check for SWT_SWITCH_DOWN in jsonENMPData.txt
  hosts: localhost
  gather_facts: no
  vars:
    regex_pattern: '"probable-cause": "SWT_SWITCH_DOWN"'
  tasks:
    - name: Read JSON data from file jsonENMPData.txt
      slurp:
        src: "jsonENMPData.txt"
      register: json_content_enmp

    - name: Check for Probable Cause in jsonENMPData.txt
      debug:
        msg: "Probable cause SWT_SWITCH_DOWN found in jsonENMPData.txt"
      when: (json_content_enmp['content'] | b64decode | regex_search(regex_pattern)) is not none


    - name: Read JSON data from file jsonNoSWTDOWN.txt
      slurp:
        src: "jsonNoSWTDOWN.txt"
      register: json_content_no_down

    - name: Check for absence of Probable Cause in jsonNoSWTDOWN.txt
      debug:
        msg: "SWT_SWITCH_DOWN not found in jsonNoSWTDOWN.txt"
      when: (json_content_no_down['content'] | b64decode | regex_search(regex_pattern)) is none
